// Autogenerated by `initGlobalsTs.ts`
export { };

declare global {
	var SUPPORTED_HTML_REWRITER_MODES: object;
	var HTML_USE_IS_ATTR: string;
	var HTML_USE_NAV_EVENTS: string;
	var FEATURE_EMU_SECURE_CTX: string;
	var FEATURE_HASH_URL: string;
	var SUPPORT_INTEGRITY_EMU: string;
	var FETCH_PUBLIC_SUFFIX_PRIORITY: string;
	var FETCH_PUBLIC_SUFFIX_HAVE_FALLBACK: string;
	var PUBLIC_SUFFIX_API: string;
	var FAILED_TO_FETCH_SUFFIX_ERR_MSG: string;
	var ERR_LOG_AFTER_COLON: string;
	var DEBUG: string;
	var FEATURE_URL_ENC: string;
	var FEATURE_CORS_TESTING: string;
	var FEATURE_CORS_EMULATIONN: string;
	var FEATURE_INTEGRITY_EMULATION: string;
	var FEATURE_ENC_BODY_EMULATION: string;
	var FEATURE_CACHES_EMULATION: string;
	var FEATURE_CLEAR_EMULATION: string;
	var REWRITER_HTML: string;
	var REWRITER_XSLT: string;
	var REWRITER_JS: string;
	var REWRITER_CACHE_MANIFEST: string;
	var SUPPORT_LEGACY: string;
	var SUPPORT_WORKER: string;
	var AERO_BRANDING_IN_PROD: string;
	var GITHUB_REPO: string;
}