name: Deploy aero CF backend
# Will be used as a fallback on aero.sh for when aero's SW can't be loaded

on:
  push:
    branches:
      - main
      - unstable

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}